<div data-mage-init='{"floatingHeader": {}}' class="page-actions"><?= $block->getButtonsHtml() ?></div>
<?= $block->getViewHtml() ?>

<h1>Description for Product Synchronisation Magento > Etsy</h1>
<br>
<p style="margin-left: 100px">
<ul style="margin-left: 100px">
    <li>
        Synchronization between Magento and Etsy. Send Products to Etsy via Etsy API
    </li>
    <li>
        For sync products - click on button Sync New Products
    </li>
    <li>
        On page "Synchronisation Tool > Add New Products" - you will see list of Categories, and count of products of
        category & products that's are already
        on Etsy portal
    </li>
    <li>
        Click on Sync to Etsy for run synchronisation process
    </li>
    <li>
        On page "Synchronisation Tool > Add New Products" - click button Refresh Sync Data - for actualise synced data
        about products
    </li>
</ul>
</p>
